<?php
    $query = 'SELECT COUNT(DISTINCT c.clientID) AS numberOfClientsWithExpiredReservations
    FROM client c
    JOIN reservation r ON c.clientID = r.clientID
    WHERE r.isExpired = "Yes"
    GROUP BY r.clientID';

    $stmt = $pdo->prepare($query);
    $stmt->execute(); 
    $clientsWithReservations = $stmt->fetchAll(); 

    $table = "client" ;
    $totalClients = countRableRows($pdo, $table) ;

    $clientsWithReservationsCount = $stmt->rowCount() ;
    $clientsWithNoReservationsCount = $totalClients - $clientsWithReservationsCount ;

    // echo "Total cleint : ". $totalClients . "<br>" ;
    // echo "The number of clients with reservation: " . $stmt->rowCount() . "<br>" ;

    $clientsWithReservationsPercentage = ($stmt->rowCount() / $totalClients) * 100;
    // echo "Percentage of clients with expired reservations: " . round($clientsWithReservationsPercentage, 2) . "%";
    
    $clientsWithNoReservationsPercentage = 100 - $clientsWithReservationsPercentage;
    // echo "Percentage of clients with no reservations: " . round($clientsWithNoReservationsPercentage, 2) . "%";
?>

<div class=" w-full bg-white rounded-lg shadow dark:bg-gray-800 px-4 py-3.5 ">

   <div class="flex justify-between items-start w-full">

      <div class="flex-col items-center  w-full">
        <div class="flex items-center mb-1">

            <div class="flex justify-between items-center w-full">
                <p class="text-black dark:text-white text-4xl font-semibold mb-1">Clients Report</p>
                <div class="flex">
                    <p class="text-2xl font-medium text-gray-500 dark:text-gray-400"> <?php echo $totalClients; ?> </p>
                    <svg class="w-8 h-8 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd"/>
                    </svg>
                </div>
            </div>

            <div data-popover id="chart-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                <div class="p-3 space-y-2">
                    <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                    <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                    <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                    <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                    <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
              </svg></a>
            </div>
            <div data-popper-arrow></div>
        </div>
      </div>
      
    </div>
   
</div>

<div class="py-6" id="pie-chart"></div>
  
</div>

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>
    
const getChartOptions = () => {
  return {
    series: [<?php echo $clientsWithNoReservationsPercentage ?>, <?php echo $clientsWithReservationsPercentage ?>],
    colors: ["#1C64F2", "#9061F9"],
    chart: {
      height: 420,
      width: "100%",
      type: "pie",
    },
    stroke: {
      colors: ["white"],
      lineCap: "",
    },
    plotOptions: {
      pie: {
        labels: {
          show: true,
        },
        size: "100%",
        dataLabels: {
          offset: -25
        }
      },
    },
    labels: [
      `Clients With No Reservations (${<?php echo $clientsWithNoReservationsCount; ?>})`,
      `Clients With Reservations (${<?php echo $clientsWithReservationsCount; ?>})`
    ],
    dataLabels: {
      enabled: true,
      style: {
        fontFamily: "Inter, sans-serif",
      },
    },
    legend: {
      position: "bottom",
      fontFamily: "Inter, sans-serif",
    },
    yaxis: {
      labels: {
        formatter: function (value) {
          return value + "%"
        },
      },
    },
    xaxis: {
      labels: {
        formatter: function (value) {
          return value  + "%"
        },
      },
      axisTicks: {
        show: false,
      },
      axisBorder: {
        show: false,
      },
    },
  }
}

if (document.getElementById("pie-chart") && typeof ApexCharts !== 'undefined') {
  const chart = new ApexCharts(document.getElementById("pie-chart"), getChartOptions());
  chart.render();
}

</script>